project:
  type: book
  output-dir: docs
  
book:
  title: "Efficacy of fungicides against brown spot of pear in Argentina"
  author: "Tudela et al."
  chapters:
    - index.qmd
    - in_vitro.qmd
    - bioassay.qmd
    - in_field.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
