project:
  type: book
  output-dir: docs
  
book:
  title: "Efficacy of fungicides against brown spot of pear in Argentina"
  chapters:
    - index.qmd
    - in_vitro.qmd
    - bioassay.qmd
    - in_field.qmd
  search: false
  sidebar:
    pinned: true
    tools:
          - icon: save
            menu:
              - text: In vitro - mycelial growth
                url:  "data/mycelial_growth.csv"
              - text: In vitro - conidia germination
                url:  "data/germination.csv"
              - text: Bioassays
                url:  "data/bioassay_data.csv"
              - text: In field
                url:  "data/field.csv"

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreport
