---
title: "In vitro experiments"
date: '`r paste("Actualizado en", Sys.Date())`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# install all packages that are not already installed
# packages <- c('here', 'pacman')
# install.packages(setdiff(packages, rownames(installed.packages())))

source(here::here("setup.R")) # here package should be installed
```

## Mycelial growth 

```{r}
raw <- import("data/mycelial_growth.csv", dec=",")

dat <- raw %>% 
  mutate_at(vars(dose, colony_diameter), as.numeric) %>% 
  mutate_at(vars(fungicide, strain, experiment, plate), as.factor) %>% 
  mutate(curve_id = interaction(fungicide:strain:experiment)) 
```

Data structure

```{r}
ftable(xtabs(~ fungicide + strain + experiment + dose, dat))
```

```{r}
str(dat)
```

Dose-response curves fitting by meta-analysis approach

```{r, eval=FALSE}
# verify drc_per_strain.R
mod_mg <- metadrm(colony_diameter ~ dose, 
               data=dat,
               fct=LL.3(),
               ind=curve_id,
               cid2=fungicide,
               struct="UN")
save(mod_mg, file= "models/invitro_mg.rds")
```

```{r}
load("models/invitro_mg.rds")
summary(mod_mg)
```

EC50 Estimates 

```{r}
ec50s <- ED(mod_mg, respLev=c(50)) %>% data.frame
# coef_mod_mg <- summary(mod_mg) %>% data.frame %>% 
#   rownames_to_column("param")  %>% 
#   separate(param, c("param", "fungicide"))
# ec50s <- coef_mod_mg %>% filter(param=="e") 
# ec50s
```

Comparing fungicides EC50 

As we compare EC50 ratios between fungicides, if the confidence interval does not contain 1, fungicides differ among them: 

```{r}
ed_comp <- EDcomp(mod_mg, 
                  percVec=c(50), 
                  percMat=rbind(c(1,1,1,1)), 
                  interval="fieller") %>% 
      data.frame %>% 
  rownames_to_column("comp") %>%
  rowwise() %>% 
  mutate(relative_to_one = f(Lower, Upper, 1)) # %>% 
  # as_huxtable() %>% 
  # set_number_format(1)
ed_comp
```


```{r, eval=FALSE}
ed_comp %>% 
  ggplot()+ 
  aes(x=comp, y=Estimate) + 
  geom_pointrange(aes(ymin = Lower, ymax = Upper, col=relative_to_one))+     
  geom_hline(yintercept = 1, linetype=2)+
  # scale_y_log10()+
  coord_flip() + 
  labs(col="Relative to 1")
```

```{r}
dat %>% 
  ggplot()+
  aes(x=dose+0.0001, y=colony_diameter, col=fungicide) +
  geom_point(size=.5) + 
  geom_smooth(method = drm, 
              method.args = list(fct = L.3()), se = F) +
    geom_smooth(aes(group=curve_id), size=.3, linetype=2,  
              method = drm, 
              method.args = list(fct = L.3()), se = F) +
  labs(title= "", x = "Dose (ppm)",  y = "Colony diameter (cm)", col= "Fungicide") + 
  scale_x_log10() +
  theme_bw(base_family=12)
```

```{r eval=FALSE}
ggsave(last_plot(), file="plots/mg_curves.jpg", width = 8, height = 6, units = "cm", scale=1.5, dpi = 300)
```

## Spore germination

```{r}
germi_raw <- import("data/germination.csv", dec=",")
germi_dat <- germi_raw %>% 
  mutate_at(vars(dose), as.numeric) %>% 
  mutate_at(vars(fungicide, strain, repetition, replicate), as.factor) %>% 
  mutate(curve_id = interaction(fungicide:strain:repetition)) %>% 
  mutate(dose_ = dose+0.0001)
```

Data structure 

```{r}
ftable(xtabs(complete.cases(germination_percent)~fungicide+dose+strain , data=germi_dat))
```

```{r}
str(germi_dat)
```

Dose-response curves fitting by meta-analysis approach

```{r, eval=FALSE}
mod_germ <- metadrm(germination_percent ~ dose_, 
               data=germi_dat,
               fct=LL.3(),
               ind=curve_id,
               cid2=fungicide,
               struct="UN")
save(mod_germ, file= "models/invitro_germ.rds")
```

```{r}
load("models/invitro_germ.rds")
summary(mod_germ) 
```

EC50´s Estimates

```{r}
ec50s_g <- ED(mod_germ, respLev=c(50)) %>% as.data.frame()
ec50s_g
```


```{r}
germ_comp <- EDcomp(mod_germ, 
       percVec=c(50), 
       percMat=rbind(c(1,1,1,1)), 
       interval="fieller")  %>% 
    data.frame %>% 
  rownames_to_column("comp") %>%
  rowwise() %>% 
  mutate(relative_to_one = f(Lower, Upper, 1))
germ_comp
```


```{r}
coef_mod_germ <- summary(mod_germ) %>% data.frame %>% 
    rownames_to_column("param")  %>% 
  separate(param, c("param", "fungicide"))

# ec50_germ <- coef_mod_germ %>% filter(param=="e") 
# ec50_germ
```


```{r, eval=FALSE}
germ_comp %>% 
  ggplot()+ 
  aes(x=comp, y=Estimate) + 
  geom_pointrange(aes(ymin = Lower, ymax = Upper, col=relative_to_one))+     
  geom_hline(yintercept = 1, linetype=2)+
  coord_flip() + 
  labs(col="Relative to 1")
```

```{r}
germi_dat %>% 
  ggplot()+
  aes(x=dose+0.0001, y=germination_percent, col=fungicide) +
  scale_x_log10() +
  geom_point(size=1) + 
  geom_smooth(method = drm, 
              method.args = list(fct = L.3()), se = F) +  
  geom_smooth(aes(group=curve_id), size=.3, linetype=2,  
              method = drm, 
              method.args = list(fct = L.3()), se = F) +
  labs(title= "", x = "Dose (ppm)",  y = "Germination (%)", col= "Fungicide")  +
  theme_bw(base_family=12)
```

```{r eval=FALSE}
ggsave(last_plot(), file="plots/germi_curves.jpg", width = 8, height = 6, units = "cm", scale=1.5, dpi = 300)
```
